import type { CollectionConfig } from 'payload'
import { hasRole, publishedReadable } from '../../access/rbac'
import { statusField, tenantIdField } from '../../access/fields'

export const SupplierSiteBlock: CollectionConfig = {
  slug: 'site-blocks',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'supplierId', 'blockType', '_status'],
    group: 'Site Builder',
  },
  access: {
    create: hasRole('superadmin', 'tenant_admin', 'supplier_admin', 'content_editor'),
    read: publishedReadable,
    update: hasRole('superadmin', 'tenant_admin', 'supplier_admin', 'content_editor'),
    delete: hasRole('superadmin', 'tenant_admin', 'supplier_admin'),
  },
  versions: { drafts: true },
  fields: [
    tenantIdField,
    { name: 'supplierId', type: 'text', required: true, index: true },
    { name: 'name', type: 'text', required: true },
    {
      name: 'blockType',
      type: 'select',
      required: true,
      index: true,
      options: [
        { label: 'Hero banner', value: 'hero' },
        { label: 'About section', value: 'about' },
        { label: 'Product grid', value: 'product_grid' },
        { label: 'Product carousel', value: 'product_carousel' },
        { label: 'Featured product', value: 'featured_product' },
        { label: 'Category showcase', value: 'category_showcase' },
        { label: 'Image gallery', value: 'gallery' },
        { label: 'Video player', value: 'video' },
        { label: 'Live stream embed', value: 'live_stream' },
        { label: '360 product viewer', value: 'spin_360' },
        { label: 'Virtual factory tour', value: 'factory_tour' },
        { label: 'Timeline', value: 'timeline' },
        { label: 'Team members', value: 'team' },
        { label: 'Testimonials', value: 'testimonials' },
        { label: 'Certifications', value: 'certifications' },
        { label: 'Awards', value: 'awards' },
        { label: 'Map / location', value: 'map' },
        { label: 'Contact form', value: 'contact_form' },
        { label: 'Chat button', value: 'chat_button' },
        { label: 'Newsletter signup', value: 'newsletter' },
        { label: 'Press / news', value: 'news' },
        { label: 'Stats counter', value: 'stats' },
        { label: 'FAQ accordion', value: 'faq' },
        { label: 'Pricing table', value: 'pricing' },
        { label: 'Catalog download', value: 'catalog_download' },
        { label: 'RFQ widget', value: 'rfq_widget' },
        { label: 'Custom HTML', value: 'custom_html' },
        { label: 'Embed', value: 'embed' },
        { label: 'Divider', value: 'divider' },
        { label: 'CTA', value: 'cta' },
      ],
    },
    {
      name: 'content',
      type: 'json',
      admin: { description: 'Block-specific structured content (varies by blockType)' },
    },
    {
      name: 'media',
      type: 'array',
      fields: [{ name: 'asset', type: 'upload', relationTo: 'media' }],
    },
    {
      name: 'style',
      type: 'group',
      fields: [
        { name: 'background', type: 'text' },
        { name: 'foreground', type: 'text' },
        { name: 'paddingY', type: 'number', defaultValue: 48 },
        { name: 'paddingX', type: 'number', defaultValue: 24 },
        { name: 'maxWidth', type: 'number', defaultValue: 1280 },
      ],
    },
    {
      name: 'visibility',
      type: 'group',
      fields: [
        { name: 'desktop', type: 'checkbox', defaultValue: true },
        { name: 'tablet', type: 'checkbox', defaultValue: true },
        { name: 'mobile', type: 'checkbox', defaultValue: true },
      ],
    },
    {
      name: 'animation',
      type: 'select',
      defaultValue: 'none',
      options: ['none', 'fade', 'slide_up', 'slide_left', 'zoom'],
    },
    statusField,
  ],
}
