-- ClickHouse 01: Databases + Replication setup
-- Apply on ClickHouse server (not PostgreSQL!)

CREATE DATABASE IF NOT EXISTS audit_ch;
CREATE DATABASE IF NOT EXISTS advertising_ch;
CREATE DATABASE IF NOT EXISTS search_ch;
CREATE DATABASE IF NOT EXISTS personalization_ch;
CREATE DATABASE IF NOT EXISTS communication_ch;
CREATE DATABASE IF NOT EXISTS live_ch;
CREATE DATABASE IF NOT EXISTS email_ch;
CREATE DATABASE IF NOT EXISTS auth_ch;
CREATE DATABASE IF NOT EXISTS rbac_ch;
CREATE DATABASE IF NOT EXISTS api_ch;
CREATE DATABASE IF NOT EXISTS payment_ch;
CREATE DATABASE IF NOT EXISTS notification_ch;
CREATE DATABASE IF NOT EXISTS experiment_ch;
CREATE DATABASE IF NOT EXISTS ai_ch;
CREATE DATABASE IF NOT EXISTS tax_ch;
CREATE DATABASE IF NOT EXISTS media_ch;
CREATE DATABASE IF NOT EXISTS fraud_ch;
CREATE DATABASE IF NOT EXISTS vn_sourcing_ch;
